EfficieNET/Models/ErrorViewModel.cs
using System;

namespace EfficieNET.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EfficieNET/Controllers/BuyRealEstatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EfficieNET.Data;
using VRtour.Lib.Models;

namespace EfficieNET.Controllers
{
    public class BuyRealEstatesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BuyRealEstatesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BuyRealEstates
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Buy.Include(b => b.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BuyRealEstates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buyRealEstate = await _context.Buy
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buyRealEstate == null)
            {
                return NotFound();
            }

            return View(buyRealEstate);
        }

        // GET: BuyRealEstates/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: BuyRealEstates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,Price,VRtourURL,City,Area,Type,Condition,PlotSizeSquareMeters,NumberOfParkingSpaces,NumberOfBalconies,NumberOfAirCondition,NumberOfBedrooms,NumberOfBathrooms,IsFurnishing,HasPool,HasGarden,HasElevator,HasAlarm,HasFireplace,HasPlayroom,HasAtticLoft,HasStorageRoom,HasSauna,CreatedDate,UpdatedDate")] BuyRealEstate buyRealEstate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(buyRealEstate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", buyRealEstate.UserId);
            return View(buyRealEstate);
        }

        // GET: BuyRealEstates/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buyRealEstate = await _context.Buy.FindAsync(id);
            if (buyRealEstate == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", buyRealEstate.UserId);
            return View(buyRealEstate);
        }

        // POST: BuyRealEstates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,Price,VRtourURL,City,Area,Type,Condition,PlotSizeSquareMeters,NumberOfParkingSpaces,NumberOfBalconies,NumberOfAirCondition,NumberOfBedrooms,NumberOfBathrooms,IsFurnishing,HasPool,HasGarden,HasElevator,HasAlarm,HasFireplace,HasPlayroom,HasAtticLoft,HasStorageRoom,HasSauna,CreatedDate,UpdatedDate")] BuyRealEstate buyRealEstate)
        {
            if (id != buyRealEstate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(buyRealEstate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BuyRealEstateExists(buyRealEstate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", buyRealEstate.UserId);
            return View(buyRealEstate);
        }

        // GET: BuyRealEstates/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buyRealEstate = await _context.Buy
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buyRealEstate == null)
            {
                return NotFound();
            }

            return View(buyRealEstate);
        }

        // POST: BuyRealEstates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var buyRealEstate = await _context.Buy.FindAsync(id);
            _context.Buy.Remove(buyRealEstate);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BuyRealEstateExists(int id)
        {
            return _context.Buy.Any(e => e.Id == id);
        }
    }
}

EfficieNET/Controllers/HomeController.cs
using EfficieNET.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EfficieNET.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EfficieNET/Views/BuyRealEstates/Create.cshtml
@model VRtour.Lib.Models.BuyRealEstate

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BuyRealEstate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VRtourURL" class="control-label"></label>
                <input asp-for="VRtourURL" class="form-control" />
                <span asp-validation-for="VRtourURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <select asp-for="City" class="form-control"></select>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <select asp-for="Area" class="form-control"></select>
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <select asp-for="Condition" class="form-control"></select>
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlotSizeSquareMeters" class="control-label"></label>
                <input asp-for="PlotSizeSquareMeters" class="form-control" />
                <span asp-validation-for="PlotSizeSquareMeters" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfParkingSpaces" class="control-label"></label>
                <input asp-for="NumberOfParkingSpaces" class="form-control" />
                <span asp-validation-for="NumberOfParkingSpaces" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfBalconies" class="control-label"></label>
                <input asp-for="NumberOfBalconies" class="form-control" />
                <span asp-validation-for="NumberOfBalconies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfAirCondition" class="control-label"></label>
                <input asp-for="NumberOfAirCondition" class="form-control" />
                <span asp-validation-for="NumberOfAirCondition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfBedrooms" class="control-label"></label>
                <input asp-for="NumberOfBedrooms" class="form-control" />
                <span asp-validation-for="NumberOfBedrooms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfBathrooms" class="control-label"></label>
                <input asp-for="NumberOfBathrooms" class="form-control" />
                <span asp-validation-for="NumberOfBathrooms" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsFurnishing" /> @Html.DisplayNameFor(model => model.IsFurnishing)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasPool" /> @Html.DisplayNameFor(model => model.HasPool)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasGarden" /> @Html.DisplayNameFor(model => model.HasGarden)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasElevator" /> @Html.DisplayNameFor(model => model.HasElevator)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasAlarm" /> @Html.DisplayNameFor(model => model.HasAlarm)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasFireplace" /> @Html.DisplayNameFor(model => model.HasFireplace)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasPlayroom" /> @Html.DisplayNameFor(model => model.HasPlayroom)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasAtticLoft" /> @Html.DisplayNameFor(model => model.HasAtticLoft)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasStorageRoom" /> @Html.DisplayNameFor(model => model.HasStorageRoom)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasSauna" /> @Html.DisplayNameFor(model => model.HasSauna)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EfficieNET/Views/BuyRealEstates/Delete.cshtml
@model VRtour.Lib.Models.BuyRealEstate

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BuyRealEstate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VRtourURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VRtourURL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Condition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Condition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlotSizeSquareMeters)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlotSizeSquareMeters)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfParkingSpaces)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfParkingSpaces)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfBalconies)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfBalconies)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfAirCondition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfAirCondition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfBedrooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfBedrooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfBathrooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfBathrooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFurnishing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsFurnishing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasPool)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasPool)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasGarden)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasGarden)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasElevator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasElevator)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasAlarm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasAlarm)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasFireplace)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasFireplace)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasPlayroom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasPlayroom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasAtticLoft)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasAtticLoft)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasStorageRoom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasStorageRoom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasSauna)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasSauna)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EfficieNET/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="row">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://my.matterport.com/show/?m=Lu8V2q29ju9" allowfullscreen></iframe>
        </div>
        @*<div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://my.matterport.com/show/?m=JDaba3GGAW6" allowfullscreen></iframe>
        </div>*@
    </div>
</div>

EfficieNET/Views/Shared/_LeftVerticalMenuLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<nav class="col-md-2 d-none d-md-block bg-light sidebar" style="min-height: calc(100vh - 118px);">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" asp-area="" asp-controller="BuyRealEstates" asp-action="Index">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                    Orders
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                    Products
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                    Customers
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                    Reports
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                    Integrations
                </a>
            </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
            </a>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                    Current month
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                    Last quarter
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                    Social engagement
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                    Year-end sale
                </a>
            </li>
        </ul>
    </div>
</nav>